enable-whitelist: false
blacklist:
  - sosi
  - admin

whitelist:
  - test
  - fuck

network:
  url: 'jdbc:mysql://localhost:3306/test'
  username: 'root'
  password: 'admin'

bot:
  #Статус бота: true - включен, false - выключен
  enabled: true
  #Токен бота
  token: ''
  #ID канала для сообщений
  channel-id: ''
  #Использование команд только в указаном канале
  command-only-channel: true
  #Локал-чат
  local-chat: true
  #Время для подтверждения связки аккаунтов (в секундах)
  authentication-time: 60
  #Время для подтверждения отвязки аккаунтов (в секундах)
  deauthentication-time: 60