network:
  url: 'jdbc:mysql://localhost:3306/test'
  username: ''
  password: ''

bot:
  #Статус бота: true - включен, false - выключен
  enabled: true
  #Токен бота
  token: ''
  #ID канала для логгирования сообщений
  channel-id: ''
  #Использование команд только в указаном канале
  command-only-channel: true
  #Логгировать локал-чат
  local-chat: true
  #Время для подтверждения связки аккаунтов (в секундах)
  verify-time: 60