name: DiscordBotLogger
version: ${project.version}
main: ru.looprich.discordlogger.DiscordLogger
load: STARTUP
authors: [LoopRich161, FrostDelta123]
description: We look console in the online mode!
commands:
  bot:
    permission: discordlogger.bot
    permission-message: U dont have permissions!
  toggle:
    permission: discordlogger.toggle
    permission-message: U dont have permissions!
